Feature/save component position
ditrit/leto-modelizer-plugin-core pull request #105
Opened 2022-11-25 13:42 UTC by sohzaz

:information_source:  Don't forget to modify the changelog.md before merging this branch.

2022-11-25 16:44 UTC, Zorin95670 requested changes

2022-11-25 16:44 UTC, Zorin95670 commented on src/models/ComponentDrawOption.js
> +    this.needsResizing = needsResizing || false;
missing test

2022-11-25 16:44 UTC, Zorin95670 commented on tests/unit/draw/DefaultDrawer.spec.js
> +    it('Should flag the parent nodes', () => {
missing space before it

2022-11-28 08:58 UTC, sohzaz commented on src/models/ComponentDrawOption.js
> +    this.needsResizing = needsResizing || false;
Added

2022-11-28 08:58 UTC, sohzaz commented on tests/unit/draw/DefaultDrawer.spec.js
> +    it('Should flag the parent nodes', () => {
done

2022-11-28 09:25 UTC, Zorin95670 approved these changes

2022-11-28 09:25 UTC, merged