Feature: Add errors detection in Component.
ditrit/leto-modelizer-plugin-core pull request #114
Opened 2022-12-01 14:03 UTC by Hundraw

Close #131

2023-01-17 14:56 UTC, k-y0u requested changes

2023-01-17 14:56 UTC, k-y0u commented on src/models/Component.js
> +   * Returns true if a required attribute is absent.
Return

2023-01-17 14:56 UTC, k-y0u commented on src/models/Component.js
> +   * Checks the types and the rules of attribute.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/Component.js
> +   * @returns {boolean} - Return true if component has an error.
wrong c/p

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks the attribute by type, and returns true if an error occurs.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +    if (this.definition.type === 'String') {
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/switch

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks String type.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks Number type.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks Boolean type.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks Object type
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks Array type.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks Link type.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * @returns {boolean} - Returns true if an error occurs.
Return

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks if min and max rules corresponding to the value or its length.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * @returns {boolean} - Returns true if the value is smaller than the "min" rules
Return

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * or larger than the "max" rules.
bigger

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Checks if the value matches with the regex rule.
Check

2023-01-17 14:56 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * @returns {boolean} - Returns true if attribute's value doesn't match with the "regex" rule.
Return

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes.length)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].definition)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes.length)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].definition)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes.length)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
>          expect(component.attributes.length)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
>          expect(component.attributes.length)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].value)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes.length)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].definition.name)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].value)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes.length)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].definition.name)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].value)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          expect(component.attributes)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          expect(component.attributes)
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.getAttributeByName('unknown'))
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.getAttributeByName('root'))
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(component.getAttributeByName('sub'))
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        expect(new Component().getContainerId())
one line

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test the "value" ("test") rule.
remove comment

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false when "values" rule does match with attribute value', () => {
the opposite

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when "values" rule doesn\'t match with attribute value', () => {
opposite

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false when attribute value between "min" and "max" rule', () => {
value is between

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test "min" (5) and "max" (10) rule.
comment to remove

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when attribute value smaller than the "min" rule', () => {
is smaller

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when attribute value taller than the "max" rule', () => {
value is bigger

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test the "regex" (/^[a-z]+$/) rule.
remove comment

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when "regex" rule doesn\'t match with attribute value', () => {
opposite

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test the type (boolean)
same

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test "min" (5) and "max" (10) rule.
remove

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when array length is taller than "max" rule', () => {
is bigger

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test the "value" (['value0', 'value1']) rule.
remove

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when "value" rule doesn\'t match with attribute value', () => {
opposite

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test "min" (1) and "max" (3) rule.
remove

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false when attribute value between the "min" and "max" rule', () => {
is between

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when attribute value smaller than the "min" rule', () => {
is smaller

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when attribute value taller than the "max" rule', () => {
is bigger

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test the type (string).
remove

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test the "value" (['value0', 'value1']) rule.
remove

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false when "value" rule does match with attribute value', () => {
opposite

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when "value" rule doesn\'t match with attribute value', () => {
opposite

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false when attribute value between the "min" and "max" rule', () => {
is between

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        // Test "min" (1) and "max" (3) rule.
remove

2023-01-17 14:56 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return true when attribute value smaller than the "min" rule', () => {
is smaller

2023-01-19 10:58 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +    if (this.definition.type === 'String') {
what was done finally ?

2023-01-19 11:06 UTC, Zorin95670 requested changes

2023-01-19 11:06 UTC, Zorin95670 commented on src/models/ComponentAttribute.js
> +      if (!regex.test(this.value)) {
can directly `return !regex.test(this.value)` here

2023-01-19 14:15 UTC, k-y0u commented
commit name :
Change data to testing hasError -> Change data to test hasError

2023-01-19 15:59 UTC, k-y0u requested changes

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toMatchObject({
put the line above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toMatchObject({
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toMatchObject({
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toMatchObject({
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toMatchObject({
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toMatchObject({
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toMatchObject({
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toEqual([new ComponentAttribute({
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        'Should remove value corresponding to the given id if the attribute if array is empty',
Should remove value from given attribute then the attribute itself if it's empty.

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toEqual([new ComponentAttribute({
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        'Should remove value corresponding to the given id if the attribute if array is empty',
undo

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "values" rule doesn\'t includes the attribute\'s value',
doesn\'t include

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the attribute\'s value doesn\'t match with the "regex" rule ',
doesn\'t match the "regex" rule'

(don't forget to delete the space at the end)

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false if the "value" rule includes the attribute\'s values', () => {
"values" rule includes the attribute\'s value

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "value" rule doesn\'t includes the attribute\'s values',
'Should return true if the "values" rule doesn\'t includes the attribute\'s value',

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false if the "value" rule includes the attribute\'s values', () => {
same

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "value" rule doesn\'t includes the attribute\'s values',
same

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false if the "value" rule includes the attribute\'s values', () => {
same

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "value" rule doesn\'t includes the attribute\'s value',
same

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false if the "value" rule does includes the attribute\'s value', () => {
same

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "value" rule doesn\'t includes the attribute\'s value',
same

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +    // Reference is like an string
remove

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +    // link is like an array
remove

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeTruthy();
above

2023-01-19 15:59 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +          .toBeFalsy();
above

2023-01-20 10:32 UTC, k-y0u commented on src/models/ComponentAttribute.js
> +   * Check if min and max rules corresponding to the value or its length.
follows OR respects !

2023-01-20 10:37 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          .toEqual([new ComponentAttribute({
nope ! L.407

2023-01-20 10:42 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the attribute\'s value doesn\'t match with the "regex" rule ',
forgot to delete 'with'

2023-01-20 10:43 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "value" rule doesn\'t includes the attribute\'s values',
nope l.806

2023-01-20 10:44 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "value" rule doesn\'t includes the attribute\'s values',
nope l.947

2023-01-20 10:46 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "value" rule doesn\'t includes the attribute\'s value',
nope l.1073

2023-01-20 10:47 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        it('Should return false if the "value" rule does includes the attribute\'s value', () => {
nope l.1107

2023-01-20 13:27 UTC, k-y0u requested changes

2023-01-20 13:27 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +    describe('Test type: Reference', () => {
jump line before

2023-01-20 13:27 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +    describe('Test type: Link', () => {
jump line before

2023-01-20 13:27 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +    describe('Test type: Array', () => {
jump line before

2023-01-20 13:27 UTC, k-y0u commented on tests/unit/models/ComponentAttribute.spec.js
> +      it('Check if value type is not equal to type', () => {
jump line before

2023-01-20 13:27 UTC, k-y0u commented on changelog.md
> -- Add `getDragTarget` method to `DefaultDrawer.js`.
why delete log ?

2023-01-20 13:27 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +        'Should remove the given ComponentLink id in the value array.',
one line

2023-01-20 13:27 UTC, k-y0u commented on tests/unit/models/Component.spec.js
> +          'Should return true if the "values" rule doesn\'t include the attribute\'s value',
one line

2023-01-20 13:47 UTC, k-y0u approved these changes

2023-01-20 15:56 UTC, Zorin95670 requested changes

2023-01-20 15:56 UTC, Zorin95670 commented on demo/src/assets/resources.js
> +            {% if hasError %}
prefere to have: 
```
{% if hasError %}
 <g class="component-error">
(...)
</g>
{% endif %}
```

2023-01-23 09:53 UTC, Zorin95670 approved these changes

2023-01-23 09:53 UTC, merged