Improvement: Pretty configuration
ditrit/leto-modelizer-plugin-core pull request #122
Opened 2022-12-12 13:01 UTC by Rahzbob

:information_source:  Don't forget to modify the changelog.md before merging this branch.

2022-12-12 13:24 UTC, k-y0u requested changes

2022-12-12 13:24 UTC, k-y0u commented on changelog.md
> +- Beautify configuration file.
beautify -> Add 2 spaces indentation to

2022-12-12 14:31 UTC, Rahzbob commented on changelog.md
> +- Beautify configuration file.
done

2022-12-12 14:43 UTC, k-y0u approved these changes

2022-12-12 14:56 UTC, Zorin95670 requested changes

2022-12-13 16:08 UTC, Zorin95670 approved these changes

2022-12-13 16:08 UTC, merged