Improvement: e2e tests
ditrit/leto-modelizer-plugin-core pull request #124
Opened 2022-12-21 15:20 UTC by Zorin95670

:information_source:  Don't forget to modify the changelog.md before merging this branch.

2022-12-21 15:46 UTC, Hundraw approved these changes

2022-12-22 11:31 UTC, justinehell requested changes

2022-12-22 11:31 UTC, justinehell commented on cypress/e2e/drag-and-drop.feature
>    Scenario: drag one component into an another, check it have valid parent
`check it have` -> `check it has`

2022-12-22 12:09 UTC, Zorin95670 commented on changelog.md
> +- Drag and drop for e2e tests
done but not like you says

2022-12-22 12:10 UTC, Zorin95670 commented on cypress/e2e/drag-and-drop.feature
>    Scenario: drag one component into an another, check it have valid parent
done

2022-12-22 12:38 UTC, justinehell approved these changes

2022-12-22 12:57 UTC, merged