Feature/add delete shortcut
ditrit/leto-modelizer-plugin-core pull request #181
Opened 2023-05-10 13:59 UTC by k-y0u

Add management of the delete shortcut to delete components and links.

2023-05-10 15:26 UTC, justinehell requested changes

2023-05-10 15:26 UTC, justinehell commented on src/draw/DefaultDrawer.js
> +  removeLinkHandler() {
No doc

2023-05-11 10:00 UTC, k-y0u commented on src/draw/DefaultDrawer.js
> +          } else if (this.actions.selection.current.__class === 'Link') {
Of course, it's possible but I don't think it's really useful. @Zorin95670, any opinion ?

2023-05-11 10:06 UTC, k-y0u commented on src/draw/DefaultDrawer.js
> +  removeComponentHandler() {
Done

2023-05-11 10:06 UTC, k-y0u commented on src/draw/DefaultDrawer.js
> +  removeLinkHandler() {
Done

2023-05-12 09:12 UTC, DimitriChauvel approved these changes

2023-05-12 09:28 UTC, Zorin95670 approved these changes

2023-05-12 09:32 UTC, justinehell approved these changes

2023-05-12 09:35 UTC, DimitriChauvel approved these changes

2023-05-12 09:39 UTC, merged