Feature: Add root folder path
ditrit/leto-modelizer-plugin-core pull request #246
Opened 2023-12-15 08:53 UTC by justinehell

Context of this PR - Bugfix name subfolder with same name as root folder broke fileExplorer 
In leto-modelizer, all path are now absolute instead of relative

In leto-modelizer-plugin-core, changes has been made related to the configuration file to only use the diagram path (without the rootFolder). The two following methods have been modified:
- `parseConfiguration`
- `renderConfiguration`

2023-12-20 14:44 UTC, k-y0u requested changes

2023-12-20 14:44 UTC, k-y0u commented on guides/migrations/0.22.0_to_X.X.X.md
> +In leto-modelizer-plugin-core, changes has been made related to the configuration file to only use the diagram path (without the root folder).
changes have been made

2023-12-20 14:48 UTC, justinehell commented on guides/migrations/0.22.0_to_X.X.X.md
> +In leto-modelizer-plugin-core, changes has been made related to the configuration file to only use the diagram path (without the root folder).
done

2023-12-21 13:55 UTC, justinehell commented
Not needed anymore

2023-12-21 13:55 UTC, closed without merging