Feature: Add links by link definition
ditrit/leto-modelizer-plugin-core pull request #94
Opened 2022-11-07 10:22 UTC by Hundraw

:information_source:  Don't forget to modify the changelog.md before merging this branch.

2022-11-08 10:45 UTC, Zorin95670 requested changes

2022-11-08 10:45 UTC, Zorin95670 commented on src/models/Component.js
> +      attribute.value.push(link.target);
```js
if (attribute && !attribute.value.includes(link.target) {
  attribute.value.push(link.target);
} else if(!attribute) {
  (...)
}
```

2022-11-09 08:53 UTC, Hundraw commented on src/models/Component.js
> +      attribute.value.push(link.target);
done

2022-11-09 09:35 UTC, Zorin95670 requested changes

2022-11-09 09:35 UTC, Zorin95670 commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].value[0]).toEqual('target01');
```js
expect(component.attributes[0].value).toEqual(['target01']);
```

2022-11-09 09:35 UTC, Zorin95670 commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].definition.name).toEqual('name02');
check value of attribute too

2022-11-09 09:35 UTC, Zorin95670 commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].definition.name).toEqual('name03');
check attribute value

2022-11-09 09:39 UTC, Hundraw commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].value[0]).toEqual('target01');
done

2022-11-09 09:39 UTC, Hundraw commented on tests/unit/models/Component.spec.js
> +        expect(component.attributes[0].definition.name).toEqual('name02');
done

2022-11-09 09:59 UTC, Zorin95670 approved these changes

2022-11-09 10:08 UTC, Zorin95670 approved these changes

2022-11-09 10:08 UTC, merged